name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "ec2-3-135-187-163.us-east-2.compute.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu"
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: yarn
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:      
      - run: chmod +x ./pm2_runner.sh
      - run: bash ./pm2_runner.sh
     
